# Generated by Django 5.1.7 on 2026-03-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0004_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='segments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
